import type {
  AdminQueueItem,
  ContractType,
  Guide,
  InternshipCycle,
  Job,
  Organisation,
  OrganisationType,
  PricingPlan,
  SalaryBand,
  Seniority,
  WorkMode,
} from './types'

export const policyAreas = [
  'Climate & Energy',
  'Digital Policy',
  'Health',
  'Trade',
  'Competition',
  'Transport',
  'Democracy',
  'Financial Services',
  'Agriculture',
  'Security',
  'Development',
  'Education',
]

export const cities = [
  'Brussels',
  'Luxembourg',
  'Strasbourg',
  'The Hague',
  'Frankfurt',
  'Vienna',
  'Geneva',
  'London',
  'Remote EU',
]

export const categories = [
  'Policy & Advocacy',
  'Communications',
  'Legal & Regulatory',
  'Research & Data',
  'Programmes & Events',
  'Public Affairs',
  'Operations',
  'Traineeships',
]

export const seniorities: Seniority[] = [
  'Trainee',
  'Junior',
  'Officer',
  'Manager',
  'Senior',
  'Director',
  'Executive',
]

export const contractTypes: ContractType[] = [
  'Permanent',
  'Fixed term',
  'Internship',
  'Consultancy',
  'Freelance',
  'Secondment',
]

export const workModes: WorkMode[] = ['On-site', 'Hybrid', 'Remote']

export const organisationTypes: OrganisationType[] = [
  'EU institution',
  'Agency',
  'NGO',
  'Think tank',
  'Trade association',
  'Public affairs',
  'Law firm',
  'Media',
  'Corporate',
  'International organisation',
]

export const languages = [
  'English',
  'French',
  'Dutch',
  'German',
  'Spanish',
  'Italian',
  'Polish',
]

export const jobs: Job[] = [
  {
    id: 'climate-policy-manager',
    title: 'Climate Policy Manager',
    organisationId: 'clean-grid-europe',
    organisation: 'Clean Grid Europe',
    logo: 'CG',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Climate & Energy', 'Transport'],
    category: 'Policy & Advocacy',
    seniority: 'Manager',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryMin: 68000,
    salaryMax: 82000,
    postedAt: '2026-06-19',
    deadline: '2026-07-12',
    verified: true,
    featured: true,
    transparentSalary: true,
    visaNote: 'EU work authorisation required',
    applyType: 'External ATS',
    summary:
      'Lead advocacy on grid investment, electrification, and industrial decarbonisation across EU files.',
    responsibilities: [
      'Own policy positions on electricity market design and grid permitting.',
      'Coordinate member briefings before ITRE and ENVI milestones.',
      'Represent the association in Brussels stakeholder roundtables.',
    ],
    requirements: [
      '5+ years in EU climate, energy, infrastructure, or public affairs.',
      'Strong drafting skills and comfort translating technical evidence.',
      'Fluent English; French is useful for Belgian stakeholder work.',
    ],
    benefits: ['Hybrid work', 'Training budget', 'Public transport pass'],
    matchReasons: ['Climate & Energy', 'Manager level', 'Salary disclosed'],
    source: 'Direct employer',
  },
  {
    id: 'digital-rights-legal-officer',
    title: 'Digital Rights Legal Officer',
    organisationId: 'civic-data-lab',
    organisation: 'Civic Data Lab',
    logo: 'CD',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Digital Policy', 'Democracy'],
    category: 'Legal & Regulatory',
    seniority: 'Officer',
    contractType: 'Fixed term',
    languages: ['English'],
    salaryMin: 52000,
    salaryMax: 61000,
    postedAt: '2026-06-21',
    deadline: '2026-07-05',
    verified: true,
    urgent: true,
    transparentSalary: true,
    visaNote: 'Belgian or EU work permit accepted',
    applyType: 'Hosted apply',
    summary:
      'Monitor AI Act implementation, data protection cases, and platform accountability files.',
    responsibilities: [
      'Prepare legal memos for policy campaigns and litigation partners.',
      'Track Commission guidance, EDPB opinions, and parliamentary scrutiny.',
      'Draft accessible explainers for civil society coalitions.',
    ],
    requirements: [
      'EU law degree or equivalent policy/legal experience.',
      'Knowledge of GDPR, DSA, DMA, or AI Act implementation.',
      'Ability to brief non-lawyer audiences without losing nuance.',
    ],
    benefits: ['Four-day summer weeks', 'Home office support', 'Paid learning days'],
    matchReasons: ['Digital Policy', 'Hosted application', 'Deadline soon'],
    source: 'Verified NGO feed',
  },
  {
    id: 'health-public-affairs-consultant',
    title: 'Health Public Affairs Consultant',
    organisationId: 'arc-public-affairs',
    organisation: 'ARC Public Affairs',
    logo: 'AP',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'On-site',
    policyAreas: ['Health', 'Competition'],
    category: 'Public Affairs',
    seniority: 'Junior',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryMin: 42000,
    salaryMax: 50000,
    postedAt: '2026-06-17',
    deadline: '2026-07-18',
    verified: true,
    featured: true,
    transparentSalary: true,
    visaNote: 'Sponsor transfer considered',
    applyType: 'Email',
    summary:
      'Support pharma, medtech, and patient-organisation accounts with monitoring, outreach, and campaign delivery.',
    responsibilities: [
      'Track ENVI, EPSCO, and Commission health-policy activity.',
      'Prepare client notes, stakeholder maps, and meeting briefs.',
      'Coordinate events, workshops, and policy roundtables.',
    ],
    requirements: [
      '1-3 years in Brussels public affairs, consultancy, or association work.',
      'Excellent written English and client-ready presentation skills.',
      'Interest in health policy, life sciences, or patient access.',
    ],
    benefits: ['Bonus plan', 'Mentoring', 'Client secondment options'],
    matchReasons: ['Health policy', 'Junior role', 'Visa note available'],
    source: 'Recruiter package',
  },
  {
    id: 'trade-policy-analyst',
    title: 'Trade Policy Analyst',
    organisationId: 'european-trade-forum',
    organisation: 'European Trade Forum',
    logo: 'ET',
    city: 'Remote EU',
    country: 'European Union',
    workMode: 'Remote',
    policyAreas: ['Trade', 'Development'],
    category: 'Research & Data',
    seniority: 'Officer',
    contractType: 'Consultancy',
    languages: ['English', 'Spanish'],
    salaryEstimate: 'EUR 450-550/day',
    postedAt: '2026-06-13',
    deadline: '2026-07-03',
    verified: true,
    transparentSalary: true,
    visaNote: 'Remote from EEA, UK, or Switzerland',
    applyType: 'External ATS',
    summary:
      'Produce evidence briefs on trade defence, supply chains, and strategic autonomy for an industry-backed forum.',
    responsibilities: [
      'Analyse legislative files, consultation responses, and WTO developments.',
      'Build concise dashboards for member committees.',
      'Support webinars with speakers from institutions and capitals.',
    ],
    requirements: [
      'Trade, economics, law, or international relations background.',
      'Comfort with data tables and policy evidence.',
      'Spanish is helpful for Latin America supply-chain work.',
    ],
    benefits: ['Fully remote', 'Flexible days', 'Travel to Brussels quarterly'],
    matchReasons: ['Remote EU', 'Trade', 'Daily-rate disclosed'],
    source: 'Partner network',
  },
  {
    id: 'financial-services-adviser',
    title: 'Financial Services Policy Adviser',
    organisationId: 'european-banking-council',
    organisation: 'European Banking Council',
    logo: 'EB',
    city: 'Frankfurt',
    country: 'Germany',
    workMode: 'Hybrid',
    policyAreas: ['Financial Services', 'Digital Policy'],
    category: 'Policy & Advocacy',
    seniority: 'Senior',
    contractType: 'Permanent',
    languages: ['English', 'German'],
    salaryMin: 79000,
    salaryMax: 96000,
    postedAt: '2026-06-10',
    deadline: '2026-07-24',
    verified: true,
    transparentSalary: true,
    visaNote: 'German work authorisation required',
    applyType: 'External ATS',
    summary:
      'Shape positions on banking union, digital euro, payments, and prudential regulation.',
    responsibilities: [
      'Lead working groups with members across Frankfurt, Brussels, and Paris.',
      'Prepare responses to ECB, EBA, and Commission consultations.',
      'Brief executives before institutional meetings.',
    ],
    requirements: [
      '6+ years in financial regulation, banking, consultancy, or supervision.',
      'Strong knowledge of EU prudential and payments policy.',
      'German language skills for Frankfurt stakeholder work.',
    ],
    benefits: ['Pension match', 'Executive briefings', 'Hybrid Frankfurt-Brussels travel'],
    matchReasons: ['Financial Services', 'Senior level', 'Frankfurt'],
    source: 'Direct employer',
  },
  {
    id: 'transport-trainee',
    title: 'Transport Policy Trainee',
    organisationId: 'green-mobility-network',
    organisation: 'Green Mobility Network',
    logo: 'GM',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Transport', 'Climate & Energy'],
    category: 'Traineeships',
    seniority: 'Trainee',
    contractType: 'Internship',
    languages: ['English'],
    salaryMin: 1750,
    salaryMax: 1750,
    postedAt: '2026-06-24',
    deadline: '2026-07-01',
    verified: true,
    paidInternship: true,
    urgent: true,
    transparentSalary: true,
    visaNote: 'Belgian internship convention not required',
    applyType: 'Hosted apply',
    summary:
      'Paid traineeship supporting rail, clean mobility, and TEN-T advocacy campaigns.',
    responsibilities: [
      'Monitor TRAN committee activity and Council working parties.',
      'Draft newsletters and policy updates for members.',
      'Support event logistics during European Mobility Week.',
    ],
    requirements: [
      'Interest in transport, climate policy, or EU institutions.',
      'Strong written English and ability to summarise files quickly.',
      'Prior Brussels experience is helpful but not required.',
    ],
    benefits: ['Paid internship', 'Mentor', 'Networking events'],
    matchReasons: ['Paid internship', 'Deadline this week', 'Hybrid'],
    source: 'Verified NGO feed',
  },
  {
    id: 'eu-agency-comms-officer',
    title: 'Communications Officer',
    organisationId: 'european-security-agency',
    organisation: 'European Security Agency',
    logo: 'ES',
    city: 'The Hague',
    country: 'Netherlands',
    workMode: 'On-site',
    policyAreas: ['Security', 'Democracy'],
    category: 'Communications',
    seniority: 'Officer',
    contractType: 'Fixed term',
    languages: ['English', 'Dutch'],
    salaryMin: 59000,
    salaryMax: 72000,
    postedAt: '2026-06-15',
    deadline: '2026-07-20',
    verified: true,
    transparentSalary: true,
    visaNote: 'EU nationality required',
    applyType: 'External ATS',
    summary:
      'Deliver institutional communications for cyber resilience, crisis response, and democratic security programmes.',
    responsibilities: [
      'Run content calendars for policy launches and annual reports.',
      'Coordinate media lines with operational and legal teams.',
      'Prepare accessible visuals and social copy for public updates.',
    ],
    requirements: [
      '3+ years in institutional, agency, or public-sector communications.',
      'Experience with sensitive policy topics and approval workflows.',
      'Dutch is an advantage for local media coordination.',
    ],
    benefits: ['EU agency benefits', 'Relocation support', 'Training scheme'],
    matchReasons: ['Agency role', 'Security', 'Transparent grade'],
    source: 'Institutional feed',
  },
  {
    id: 'agri-food-campaign-lead',
    title: 'Agri-Food Campaign Lead',
    organisationId: 'soil-future-alliance',
    organisation: 'Soil Future Alliance',
    logo: 'SF',
    city: 'Vienna',
    country: 'Austria',
    workMode: 'Remote',
    policyAreas: ['Agriculture', 'Climate & Energy'],
    category: 'Programmes & Events',
    seniority: 'Manager',
    contractType: 'Fixed term',
    languages: ['English', 'German'],
    salaryMin: 61000,
    salaryMax: 72000,
    postedAt: '2026-06-12',
    deadline: '2026-07-26',
    verified: true,
    transparentSalary: true,
    visaNote: 'Remote in Austria, Germany, Belgium, or Netherlands',
    applyType: 'Email',
    summary:
      'Build a coalition campaign on soil health, farm transition funding, and sustainable food systems.',
    responsibilities: [
      'Coordinate NGOs, farmers, scientists, and foundation partners.',
      'Plan policy moments around AGRI committee votes and Council conclusions.',
      'Manage a small campaign budget and creative agency.',
    ],
    requirements: [
      'Campaign leadership experience in food, farming, climate, or biodiversity.',
      'Coalition management and excellent written advocacy skills.',
      'German language skills for Austrian and German partners.',
    ],
    benefits: ['Remote-first', 'Travel budget', 'Wellbeing allowance'],
    matchReasons: ['Remote', 'Agriculture', 'German useful'],
    source: 'Foundation partner',
  },
  {
    id: 'competition-associate',
    title: 'EU Competition Associate',
    organisationId: 'nord-law-europe',
    organisation: 'Nord Law Europe',
    logo: 'NL',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'On-site',
    policyAreas: ['Competition', 'Digital Policy'],
    category: 'Legal & Regulatory',
    seniority: 'Senior',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryEstimate: 'Competitive law firm package',
    postedAt: '2026-06-18',
    deadline: '2026-08-02',
    verified: true,
    visaNote: 'Bar admission route required',
    applyType: 'External ATS',
    summary:
      'Advise clients on EU competition, state aid, platform regulation, and merger control.',
    responsibilities: [
      'Draft submissions and economic evidence narratives.',
      'Support hearings and Commission engagement.',
      'Collaborate with digital regulatory and trade teams.',
    ],
    requirements: [
      'EU competition law experience from firm, authority, or consultancy.',
      'Excellent drafting and client-management skills.',
      'French is useful for Belgian proceedings and client work.',
    ],
    benefits: ['Bonus plan', 'Secondment options', 'Private health cover'],
    matchReasons: ['Competition', 'Law firm', 'Senior'],
    source: 'Recruiter package',
  },
  {
    id: 'eu-media-editor',
    title: 'EU Policy Editor',
    organisationId: 'policy-wire-europe',
    organisation: 'Policy Wire Europe',
    logo: 'PW',
    city: 'London',
    country: 'United Kingdom',
    workMode: 'Hybrid',
    policyAreas: ['Democracy', 'Financial Services', 'Trade'],
    category: 'Communications',
    seniority: 'Director',
    contractType: 'Permanent',
    languages: ['English'],
    salaryMin: 72000,
    salaryMax: 88000,
    postedAt: '2026-06-08',
    deadline: '2026-07-29',
    verified: true,
    transparentSalary: true,
    visaNote: 'UK work authorisation required',
    applyType: 'External ATS',
    summary:
      'Lead premium EU policy coverage for subscribers across London and Brussels.',
    responsibilities: [
      'Commission analysis on financial services, trade, and institutional politics.',
      'Edit daily briefings and manage two policy reporters.',
      'Host subscriber briefings with senior EU stakeholders.',
    ],
    requirements: [
      'Editorial leadership in EU policy, finance, or Westminster-Brussels coverage.',
      'Sharp judgement on subscriber value and regulatory detail.',
      'Confidence moderating senior policy conversations.',
    ],
    benefits: ['Subscriber-event budget', 'Hybrid newsroom', 'Editor bonus'],
    matchReasons: ['Media', 'Director level', 'Salary disclosed'],
    source: 'Media partner',
  },
  {
    id: 'education-programme-officer',
    title: 'Education Programme Officer',
    organisationId: 'european-learning-foundation',
    organisation: 'European Learning Foundation',
    logo: 'EL',
    city: 'Strasbourg',
    country: 'France',
    workMode: 'Hybrid',
    policyAreas: ['Education', 'Democracy'],
    category: 'Programmes & Events',
    seniority: 'Officer',
    contractType: 'Fixed term',
    languages: ['English', 'French'],
    salaryMin: 48000,
    salaryMax: 56000,
    postedAt: '2026-06-11',
    deadline: '2026-07-15',
    verified: true,
    transparentSalary: true,
    visaNote: 'French work authorisation required',
    applyType: 'Hosted apply',
    summary:
      'Manage grants, civic education projects, and youth participation events around European democracy.',
    responsibilities: [
      'Coordinate grantees across 12 countries and track deliverables.',
      'Prepare programme reports for institutional donors.',
      'Run Strasbourg workshops with civil society partners.',
    ],
    requirements: [
      'Programme management experience in education, democracy, or civil society.',
      'Comfort with grant reporting and multilingual stakeholders.',
      'French required for local partner coordination.',
    ],
    benefits: ['Training stipend', 'Extra leave days', 'Hybrid Strasbourg office'],
    matchReasons: ['Education', 'Hosted apply', 'French'],
    source: 'Direct employer',
  },
]

export const organisations: Organisation[] = [
  {
    id: 'clean-grid-europe',
    name: 'Clean Grid Europe',
    type: 'Trade association',
    logo: 'CG',
    city: 'Brussels',
    country: 'Belgium',
    policyAreas: ['Climate & Energy', 'Transport'],
    openRoles: 3,
    verified: true,
    salaryTransparency: 91,
    hiringVelocity: 'High',
    followers: '18.4k',
    website: 'https://example.org/clean-grid',
    description:
      'Association representing grid, storage, and electrification companies in EU climate policy.',
    badges: ['Verified employer', 'Salary disclosed', 'Paid internships'],
  },
  {
    id: 'civic-data-lab',
    name: 'Civic Data Lab',
    type: 'NGO',
    logo: 'CD',
    city: 'Brussels',
    country: 'Belgium',
    policyAreas: ['Digital Policy', 'Democracy'],
    openRoles: 2,
    verified: true,
    salaryTransparency: 96,
    hiringVelocity: 'Medium',
    followers: '12.1k',
    website: 'https://example.org/civic-data',
    description:
      'Civil society team working on digital rights, public-interest technology, and AI accountability.',
    badges: ['Verified NGO', 'Hosted apply', 'Flexible work'],
  },
  {
    id: 'arc-public-affairs',
    name: 'ARC Public Affairs',
    type: 'Public affairs',
    logo: 'AP',
    city: 'Brussels',
    country: 'Belgium',
    policyAreas: ['Health', 'Competition', 'Digital Policy'],
    openRoles: 5,
    verified: true,
    salaryTransparency: 74,
    hiringVelocity: 'High',
    followers: '9.8k',
    website: 'https://example.org/arc-public-affairs',
    description:
      'Mid-size Brussels consultancy advising health, technology, and regulated-industry clients.',
    badges: ['Verified employer', 'Fast response', 'Client secondments'],
  },
  {
    id: 'european-trade-forum',
    name: 'European Trade Forum',
    type: 'Think tank',
    logo: 'ET',
    city: 'Remote EU',
    country: 'European Union',
    policyAreas: ['Trade', 'Development'],
    openRoles: 1,
    verified: true,
    salaryTransparency: 88,
    hiringVelocity: 'Low',
    followers: '6.2k',
    website: 'https://example.org/trade-forum',
    description:
      'Research forum producing evidence on trade defence, supply chains, and open strategic autonomy.',
    badges: ['Remote roles', 'Daily rates disclosed', 'Research led'],
  },
  {
    id: 'european-banking-council',
    name: 'European Banking Council',
    type: 'Trade association',
    logo: 'EB',
    city: 'Frankfurt',
    country: 'Germany',
    policyAreas: ['Financial Services', 'Digital Policy'],
    openRoles: 2,
    verified: true,
    salaryTransparency: 83,
    hiringVelocity: 'Medium',
    followers: '21.6k',
    website: 'https://example.org/banking-council',
    description:
      'Financial-sector body engaging EU and supervisory institutions on banking and payments policy.',
    badges: ['Verified employer', 'Executive exposure', 'Hybrid'],
  },
  {
    id: 'green-mobility-network',
    name: 'Green Mobility Network',
    type: 'NGO',
    logo: 'GM',
    city: 'Brussels',
    country: 'Belgium',
    policyAreas: ['Transport', 'Climate & Energy'],
    openRoles: 4,
    verified: true,
    salaryTransparency: 100,
    hiringVelocity: 'High',
    followers: '15.9k',
    website: 'https://example.org/green-mobility',
    description:
      'Coalition campaigning for clean transport, rail investment, and safer urban mobility.',
    badges: ['Paid internships', 'Transparent pay', 'Coalition work'],
  },
]

export const pricingPlans: PricingPlan[] = [
  {
    name: 'Basic Listing',
    price: 'EUR 99',
    description: 'For one targeted EU affairs vacancy with a clean public job page.',
    features: [
      '30 days live',
      'JobPosting schema',
      'Employer profile link',
      'Manual moderation',
      'Application URL or email',
    ],
    addOns: ['Newsletter mention', 'Social repost'],
  },
  {
    name: 'Pro Campaign',
    price: 'EUR 299',
    description: 'Featured distribution for priority Brussels and EU policy hiring.',
    highlight: true,
    features: [
      '60 days live',
      'Featured placement',
      'Segmented job alerts',
      'Salary quality prompt',
      'Performance analytics',
      '7-day no-application refund review',
    ],
    addOns: ['Top employer logo bar', 'Candidate Boost'],
  },
  {
    name: 'Recruiter Suite',
    price: 'EUR 500',
    description: 'For repeat recruiters that need bulk tools, branding, and tracking.',
    features: [
      '90 days live',
      'Bulk posting and duplicate jobs',
      'Custom employer branding',
      'Hosted apply forms',
      'ATS source tracking',
      'Account manager review',
    ],
    addOns: ['Newsletter sponsorship', 'Banner campaign'],
  },
]

export const salaryBands: SalaryBand[] = [
  {
    role: 'Public Affairs Manager',
    city: 'Brussels',
    seniority: 'Manager',
    low: 58000,
    median: 71000,
    high: 88000,
    sample: 146,
  },
  {
    role: 'Policy Officer',
    city: 'Brussels',
    seniority: 'Officer',
    low: 42000,
    median: 52000,
    high: 64000,
    sample: 212,
  },
  {
    role: 'Legal Associate',
    city: 'Brussels',
    seniority: 'Senior',
    low: 76000,
    median: 94000,
    high: 125000,
    sample: 64,
  },
  {
    role: 'EU Trainee',
    city: 'Brussels',
    seniority: 'Trainee',
    low: 1400,
    median: 1750,
    high: 2200,
    sample: 188,
  },
]

export const internshipCycles: InternshipCycle[] = [
  {
    name: 'Blue Book Traineeship',
    organiser: 'European Commission',
    window: 'Applications expected August 2026',
    start: 'March 2027',
    paid: true,
    notes: 'Best for candidates with EU languages, public policy, law, economics, or communications.',
  },
  {
    name: 'Schuman Traineeship',
    organiser: 'European Parliament',
    window: 'Applications expected October 2026',
    start: 'March 2027',
    paid: true,
    notes: 'Strong option for parliamentary, communications, legal, and political group experience.',
  },
  {
    name: 'Agency Traineeship Cycle',
    organiser: 'EU Agencies',
    window: 'Rolling deadlines by agency',
    start: 'Rolling',
    paid: true,
    notes: 'Track decentralised agencies by policy field, city, and language requirements.',
  },
]

export const guides: Guide[] = [
  {
    title: 'How to Break Into Brussels Public Affairs in 2026',
    tag: 'Career Guide',
    readTime: '9 min',
    description:
      'Role ladders, first-job signals, networking channels, and what recruiters expect from junior profiles.',
  },
  {
    title: 'EU Affairs Salary Report: Pay Transparency Before 2027',
    tag: 'Fair Pay',
    readTime: '12 min',
    description:
      'Benchmarks by role, seniority, policy area, and organisation type, with notes for unpaid internship screening.',
  },
  {
    title: 'Writing Job Ads That Attract Better EU Policy Candidates',
    tag: 'Recruiter Playbook',
    readTime: '7 min',
    description:
      'A practical checklist for salary ranges, deadlines, languages, visa signals, and non-generic responsibilities.',
  },
]

export const adminQueue: AdminQueueItem[] = [
  {
    id: 'queue-1',
    label: 'Unknown Company import: missing logo and salary conflict',
    type: 'Job review',
    risk: 'High',
    status: 'Needs verification',
  },
  {
    id: 'queue-2',
    label: 'Green Mobility Network internship salary verified',
    type: 'Salary estimate',
    risk: 'Low',
    status: 'Ready to approve',
  },
  {
    id: 'queue-3',
    label: 'Duplicate policy consultant posting detected',
    type: 'Report',
    risk: 'Medium',
    status: 'Compare apply links',
  },
]

export const recruiterMetrics = [
  { label: 'Qualified applies', value: '2,846', change: '+18%' },
  { label: 'Alert impressions', value: '184k', change: '+31%' },
  { label: 'Median apply rate', value: '8.7%', change: '+2.1 pts' },
  { label: 'Salary disclosed roles', value: '76%', change: '+14 pts' },
]

export const transparencyEntities = [
  {
    name: 'European Renewable Alliance',
    type: 'Trade association',
    interests: ['Climate & Energy', 'Industrial policy'],
    country: 'Belgium',
    registered: '2018',
    relatedJobs: 6,
    spend: 'EUR 1.0m-1.25m',
    hiringSignal: 'Hiring policy and campaigns teams',
  },
  {
    name: 'Digital Rights Observatory',
    type: 'NGO',
    interests: ['Digital Policy', 'Democracy'],
    country: 'Belgium',
    registered: '2015',
    relatedJobs: 3,
    spend: 'EUR 300k-399k',
    hiringSignal: 'Frequent legal and research fellowships',
  },
  {
    name: 'Food Systems Forum',
    type: 'Think tank',
    interests: ['Agriculture', 'Health'],
    country: 'France',
    registered: '2021',
    relatedJobs: 2,
    spend: 'EUR 100k-199k',
    hiringSignal: 'Project-funded research roles',
  },
]

export const brusselsBest = [
  {
    category: 'Public affairs consultancies',
    count: 184,
    standout: 'Health, tech, energy, competition, and trade specialists with verified client sectors.',
  },
  {
    category: 'EU law firms',
    count: 96,
    standout: 'Competition, state aid, sanctions, privacy, trade defence, and product regulation teams.',
  },
  {
    category: 'Policy intelligence tools',
    count: 42,
    standout: 'Legislative monitoring, stakeholder mapping, amendments, and alerting platforms.',
  },
  {
    category: 'Trainers and career coaches',
    count: 68,
    standout: 'Interview prep, EU writing, advocacy training, institutional simulation, and language coaching.',
  },
]

export const postingRequirements = [
  'Job title',
  'Company and verified employer profile',
  'Category, seniority, contract type, and work mode',
  'City, country, remote eligibility, and right-to-work note',
  'Salary range or salary-estimate justification',
  'Application URL or email route',
  'Hiring contact name, email, and phone',
  'Expiry date and moderation notes',
  'Up to four policy tags',
  'Block AI-generated applications flag',
]

export const alertPreferences = [
  'Keyword and employer-follow alerts',
  'Policy area, seniority, contract, and location filters',
  'Salary-disclosed-only toggle',
  'Deadline-soon reminders',
  'Instant, daily, weekly, and newsletter frequencies',
  'Anonymous saved search migration after signup',
]

export const featureChecklist = [
  'Advanced search across keyword, city, policy area, seniority, contract, language, salary, deadline, work mode, and organisation type.',
  'Job detail pages with verified employer data, salary bands, deadline status, source links, share/save actions, and structured sections.',
  'Job alerts for instant, daily, or weekly delivery with saved-search criteria and employer-follow options.',
  'Company directory with verified employers, open-role counts, salary transparency, hiring velocity, and policy areas.',
  'Lobbying and transparency-register intelligence with entity filters, related jobs, and career-guide links.',
  'Brussels Best style supplier directory for consultancies, law firms, tools, trainers, and policy specialists.',
  'Fair Pay salary explorer by role, city, seniority, policy area, organisation type, and sample size.',
  'Internship calendar for EU institutions, agencies, NGOs, embassies, party groups, and recurring traineeships.',
  'Recruiter dashboard with guided posting, quality score, bulk posting, analytics, invoices, add-ons, and moderation feedback.',
  'SEO package: JobPosting, Organization, BreadcrumbList, Article, FAQ schema, sitemap, robots rules, Open Graph, and canonical URLs.',
]
