import type {
  AdminQueueItem,
  ContractType,
  Guide,
  InternshipCycle,
  Job,
  Organisation,
  OrganisationType,
  PricingPlan,
  SalaryBand,
  Seniority,
  WorkMode,
} from './types'

export const policyAreas = [
  'Climate & Energy',
  'Digital Policy',
  'Health',
  'Trade',
  'Competition',
  'Transport',
  'Democracy',
  'Financial Services',
  'Agriculture',
  'Security',
  'Development',
  'Education',
]

export const cities = [
  'Brussels',
  'Luxembourg',
  'Strasbourg',
  'The Hague',
  'Frankfurt',
  'Vienna',
  'Geneva',
  'London',
  'Remote EU',
]

export const categories = [
  'Policy & Advocacy',
  'Communications',
  'Legal & Regulatory',
  'Research & Data',
  'Programmes & Events',
  'Public Affairs',
  'Operations',
  'Traineeships',
]

export const seniorities: Seniority[] = [
  'Trainee',
  'Junior',
  'Officer',
  'Manager',
  'Senior',
  'Director',
  'Executive',
]

export const contractTypes: ContractType[] = [
  'Permanent',
  'Fixed term',
  'Internship',
  'Consultancy',
  'Freelance',
  'Secondment',
]

export const workModes: WorkMode[] = ['On-site', 'Hybrid', 'Remote']

export const organisationTypes: OrganisationType[] = [
  'EU institution',
  'Agency',
  'NGO',
  'Think tank',
  'Trade association',
  'Public affairs',
  'Law firm',
  'Media',
  'Corporate',
  'International organisation',
]

export const languages = [
  'English',
  'French',
  'Dutch',
  'German',
  'Spanish',
  'Italian',
  'Polish',
]

export const jobs: Job[] = [
  {
    id: 'climate-policy-manager',
    title: 'Climate Policy Manager',
    organisationId: 'clean-grid-europe',
    organisation: 'Clean Grid Europe',
    logo: 'CG',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Climate & Energy', 'Transport'],
    category: 'Policy & Advocacy',
    seniority: 'Manager',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryMin: 68000,
    salaryMax: 82000,
    postedAt: '2026-06-19',
    deadline: '2026-07-12',
    verified: true,
    featured: true,
    transparentSalary: true,
    visaNote: 'EU work authorisation required',
    applyType: 'External ATS',
    summary:
      'Lead advocacy on grid investment, electrification, and industrial decarbonisation across EU files.',
    responsibilities: [
      'Own policy positions on electricity market design and grid permitting.',
      'Coordinate member briefings before ITRE and ENVI milestones.',
      'Represent the association in Brussels stakeholder roundtables.',
    ],
    requirements: [
      '5+ years in EU climate, energy, infrastructure, or public affairs.',
      'Strong drafting skills and comfort translating technical evidence.',
      'Fluent English; French is useful for Belgian stakeholder work.',
    ],
    benefits: ['Hybrid work', 'Training budget', 'Public transport pass'],
    matchReasons: ['Climate & Energy', 'Manager level', 'Salary disclosed'],
    source: 'Direct employer',
  },
  {
    id: 'digital-rights-legal-officer',
    title: 'Digital Rights Legal Officer',
    organisationId: 'civic-data-lab',
    organisation: 'Civic Data Lab',
    logo: 'CD',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Digital Policy', 'Democracy'],
    category: 'Legal & Regulatory',
    seniority: 'Officer',
    contractType: 'Fixed term',
    languages: ['English'],
    salaryMin: 52000,
    salaryMax: 61000,
    postedAt: '2026-06-21',
    deadline: '2026-07-05',
    verified: true,
    urgent: true,
    transparentSalary: true,
    visaNote: 'Belgian or EU work permit accepted',
    applyType: 'Hosted apply',
    summary:
      'Monitor AI Act implementation, data protection cases, and platform accountability files.',
    responsibilities: [
      'Prepare legal memos for policy campaigns and litigation partners.',
      'Track Commission guidance, EDPB opinions, and parliamentary scrutiny.',
      'Draft accessible explainers for civil society coalitions.',
    ],
    requirements: [
      'EU law degree or equivalent policy/legal experience.',
      'Knowledge of GDPR, DSA, DMA, or AI Act implementation.',
      'Ability to brief non-lawyer audiences without losing nuance.',
    ],
    benefits: ['Four-day summer weeks', 'Home office support', 'Paid learning days'],
    matchReasons: ['Digital Policy', 'Hosted application', 'Deadline soon'],
    source: 'Verified NGO feed',
  },
  {
    id: 'health-public-affairs-consultant',
    title: 'Health Public Affairs Consultant',
    organisationId: 'arc-public-affairs',
    organisation: 'ARC Public Affairs',
    logo: 'AP',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'On-site',
    policyAreas: ['Health', 'Competition'],
    category: 'Public Affairs',
    seniority: 'Junior',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryMin: 42000,
    salaryMax: 50000,
    postedAt: '2026-06-17',
    deadline: '2026-07-18',
    verified: true,
    featured: true,
    transparentSalary: true,
    visaNote: 'Sponsor transfer considered',
    applyType: 'Email',
    summary:
      'Support pharma, medtech, and patient-organisation accounts with monitoring, outreach, and campaign delivery.',
    responsibilities: [
      'Track ENVI, EPSCO, and Commission health-policy activity.',
      'Prepare client notes, stakeholder maps, and meeting briefs.',
      'Coordinate events, workshops, and policy roundtables.',
    ],
    requirements: [
      '1-3 years in Brussels public affairs, consultancy, or association work.',
      'Excellent written English and client-ready presentation skills.',
      'Interest in health policy, life sciences, or patient access.',
    ],
    benefits: ['Bonus plan', 'Mentoring', 'Client secondment options'],
    matchReasons: ['Health policy', 'Junior role', 'Visa note available'],
    source: 'Recruiter package',
  },
  {
    id: 'trade-policy-analyst',
    title: 'Trade Policy Analyst',
    organisationId: 'european-trade-forum',
    organisation: 'European Trade Forum',
    logo: 'ET',
    city: 'Remote EU',
    country: 'European Union',
    workMode: 'Remote',
    policyAreas: ['Trade', 'Development'],
    category: 'Research & Data',
    seniority: 'Officer',
    contractType: 'Consultancy',
    languages: ['English', 'Spanish'],
    salaryEstimate: 'EUR 450-550/day',
    postedAt: '2026-06-13',
    deadline: '2026-07-03',
    verified: true,
    transparentSalary: true,
    visaNote: 'Remote from EEA, UK, or Switzerland',
    applyType: 'External ATS',
    summary:
      'Produce evidence briefs on trade defence, supply chains, and strategic autonomy for an industry-backed forum.',
    responsibilities: [
      'Analyse legislative files, consultation responses, and WTO developments.',
      'Build concise dashboards for member committees.',
      'Support webinars with speakers from institutions and capitals.',
    ],
    requirements: [
      'Trade, economics, law, or international relations background.',
      'Comfort with data tables and policy evidence.',
      'Spanish is helpful for Latin America supply-chain work.',
    ],
    benefits: ['Fully remote', 'Flexible days', 'Travel to Brussels quarterly'],
    matchReasons: ['Remote EU', 'Trade', 'Daily-rate disclosed'],
    source: 'Partner network',
  },
]
