import type {
  AdminQueueItem,
  ContractType,
  Guide,
  InternshipCycle,
  Job,
  Organisation,
  OrganisationType,
  PricingPlan,
  SalaryBand,
  Seniority,
  WorkMode,
} from './types'

export const policyAreas = [
  'Climate & Energy',
  'Digital Policy',
  'Health',
  'Trade',
  'Competition',
  'Transport',
  'Democracy',
  'Financial Services',
  'Agriculture',
  'Security',
  'Development',
  'Education',
]

export const cities = [
  'Brussels',
  'Luxembourg',
  'Strasbourg',
  'The Hague',
  'Frankfurt',
  'Vienna',
  'Geneva',
  'London',
  'Remote EU',
]

export const categories = [
  'Policy & Advocacy',
  'Communications',
  'Legal & Regulatory',
  'Research & Data',
  'Programmes & Events',
  'Public Affairs',
  'Operations',
  'Traineeships',
]

export const seniorities: Seniority[] = [
  'Trainee',
  'Junior',
  'Officer',
  'Manager',
  'Senior',
  'Director',
  'Executive',
]

export const contractTypes: ContractType[] = [
  'Permanent',
  'Fixed term',
  'Internship',
  'Consultancy',
  'Freelance',
  'Secondment',
]

export const workModes: WorkMode[] = ['On-site', 'Hybrid', 'Remote']

export const organisationTypes: OrganisationType[] = [
  'EU institution',
  'Agency',
  'NGO',
  'Think tank',
  'Trade association',
  'Public affairs',
  'Law firm',
  'Media',
  'Corporate',
  'International organisation',
]

export const languages = [
  'English',
  'French',
  'Dutch',
  'German',
  'Spanish',
  'Italian',
  'Polish',
]

export const jobs: Job[] = [
  {
    id: 'climate-policy-manager',
    title: 'Climate Policy Manager',
    organisationId: 'clean-grid-europe',
    organisation: 'Clean Grid Europe',
    logo: 'CG',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Climate & Energy', 'Transport'],
    category: 'Policy & Advocacy',
    seniority: 'Manager',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryMin: 68000,
    salaryMax: 82000,
    postedAt: '2026-06-19',
    deadline: '2026-07-12',
    verified: true,
    featured: true,
    transparentSalary: true,
    visaNote: 'EU work authorisation required',
    applyType: 'External ATS',
    summary:
      'Lead advocacy on grid investment, electrification, and industrial decarbonisation across EU files.',
    responsibilities: [
      'Own policy positions on electricity market design and grid permitting.',
      'Coordinate member briefings before ITRE and ENVI milestones.',
      'Represent the association in Brussels stakeholder roundtables.',
    ],
    requirements: [
      '5+ years in EU climate, energy, infrastructure, or public affairs.',
      'Strong drafting skills and comfort translating technical evidence.',
      'Fluent English; French is useful for Belgian stakeholder work.',
    ],
    benefits: ['Hybrid work', 'Training budget', 'Public transport pass'],
    matchReasons: ['Climate & Energy', 'Manager level', 'Salary disclosed'],
    source: 'Direct employer',
  },
  {
    id: 'digital-rights-legal-officer',
    title: 'Digital Rights Legal Officer',
    organisationId: 'civic-data-lab',
    organisation: 'Civic Data Lab',
    logo: 'CD',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Digital Policy', 'Democracy'],
    category: 'Legal & Regulatory',
    seniority: 'Officer',
    contractType: 'Fixed term',
    languages: ['English'],
    salaryMin: 52000,
    salaryMax: 61000,
    postedAt: '2026-06-21',
    deadline: '2026-07-05',
    verified: true,
    urgent: true,
    transparentSalary: true,
    visaNote: 'Belgian or EU work permit accepted',
    applyType: 'Hosted apply',
    summary:
      'Monitor AI Act implementation, data protection cases, and platform accountability files.',
    responsibilities: [
      'Prepare legal memos for policy campaigns and litigation partners.',
      'Track Commission guidance, EDPB opinions, and parliamentary scrutiny.',
      'Draft accessible explainers for civil society coalitions.',
    ],
    requirements: [
      'EU law degree or equivalent policy/legal experience.',
      'Knowledge of GDPR, DSA, DMA, or AI Act implementation.',
      'Ability to brief non-lawyer audiences without losing nuance.',
    ],
    benefits: ['Four-day summer weeks', 'Home office support', 'Paid learning days'],
    matchReasons: ['Digital Policy', 'Hosted application', 'Deadline soon'],
    source: 'Verified NGO feed',
  },
  {
    id: 'health-public-affairs-consultant',
    title: 'Health Public Affairs Consultant',
    organisationId: 'arc-public-affairs',
    organisation: 'ARC Public Affairs',
    logo: 'AP',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'On-site',
    policyAreas: ['Health', 'Competition'],
    category: 'Public Affairs',
    seniority: 'Junior',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryMin: 42000,
    salaryMax: 50000,
    postedAt: '2026-06-17',
    deadline: '2026-07-18',
    verified: true,
    featured: true,
    transparentSalary: true,
    visaNote: 'Sponsor transfer considered',
    applyType: 'Email',
    summary:
      'Support pharma, medtech, and patient-organisation accounts with monitoring, outreach, and campaign delivery.',
    responsibilities: [
      'Track ENVI, EPSCO, and Commission health-policy activity.',
      'Prepare client notes, stakeholder maps, and meeting briefs.',
      'Coordinate events, workshops, and policy roundtables.',
    ],
    requirements: [
      '1-3 years in Brussels public affairs, consultancy, or association work.',
      'Excellent written English and client-ready presentation skills.',
      'Interest in health policy, life sciences, or patient access.',
    ],
    benefits: ['Bonus plan', 'Mentoring', 'Client secondment options'],
    matchReasons: ['Health policy', 'Junior role', 'Visa note available'],
    source: 'Recruiter package',
  },
  {
    id: 'trade-policy-analyst',
    title: 'Trade Policy Analyst',
    organisationId: 'european-trade-forum',
    organisation: 'European Trade Forum',
    logo: 'ET',
    city: 'Remote EU',
    country: 'European Union',
    workMode: 'Remote',
    policyAreas: ['Trade', 'Development'],
    category: 'Research & Data',
    seniority: 'Officer',
    contractType: 'Consultancy',
    languages: ['English', 'Spanish'],
    salaryEstimate: 'EUR 450-550/day',
    postedAt: '2026-06-13',
    deadline: '2026-07-03',
    verified: true,
    transparentSalary: true,
    visaNote: 'Remote from EEA, UK, or Switzerland',
    applyType: 'External ATS',
    summary:
      'Produce evidence briefs on trade defence, supply chains, and strategic autonomy for an industry-backed forum.',
    responsibilities: [
      'Analyse legislative files, consultation responses, and WTO developments.',
      'Build concise dashboards for member committees.',
      'Support webinars with speakers from institutions and capitals.',
    ],
    requirements: [
      'Trade, economics, law, or international relations background.',
      'Comfort with data tables and policy evidence.',
      'Spanish is helpful for Latin America supply-chain work.',
    ],
    benefits: ['Fully remote', 'Flexible days', 'Travel to Brussels quarterly'],
    matchReasons: ['Remote EU', 'Trade', 'Daily-rate disclosed'],
    source: 'Partner network',
  },
  {
    id: 'financial-services-adviser',
    title: 'Financial Services Policy Adviser',
    organisationId: 'european-banking-council',
    organisation: 'European Banking Council',
    logo: 'EB',
    city: 'Frankfurt',
    country: 'Germany',
    workMode: 'Hybrid',
    policyAreas: ['Financial Services', 'Digital Policy'],
    category: 'Policy & Advocacy',
    seniority: 'Senior',
    contractType: 'Permanent',
    languages: ['English', 'German'],
    salaryMin: 79000,
    salaryMax: 96000,
    postedAt: '2026-06-10',
    deadline: '2026-07-24',
    verified: true,
    transparentSalary: true,
    visaNote: 'German work authorisation required',
    applyType: 'External ATS',
    summary:
      'Shape positions on banking union, digital euro, payments, and prudential regulation.',
    responsibilities: [
      'Lead working groups with members across Frankfurt, Brussels, and Paris.',
      'Prepare responses to ECB, EBA, and Commission consultations.',
      'Brief executives before institutional meetings.',
    ],
    requirements: [
      '6+ years in financial regulation, banking, consultancy, or supervision.',
      'Strong knowledge of EU prudential and payments policy.',
      'German language skills for Frankfurt stakeholder work.',
    ],
    benefits: ['Pension match', 'Executive briefings', 'Hybrid Frankfurt-Brussels travel'],
    matchReasons: ['Financial Services', 'Senior level', 'Frankfurt'],
    source: 'Direct employer',
  },
  {
    id: 'transport-trainee',
    title: 'Transport Policy Trainee',
    organisationId: 'green-mobility-network',
    organisation: 'Green Mobility Network',
    logo: 'GM',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'Hybrid',
    policyAreas: ['Transport', 'Climate & Energy'],
    category: 'Traineeships',
    seniority: 'Trainee',
    contractType: 'Internship',
    languages: ['English'],
    salaryMin: 1750,
    salaryMax: 1750,
    postedAt: '2026-06-24',
    deadline: '2026-07-01',
    verified: true,
    paidInternship: true,
    urgent: true,
    transparentSalary: true,
    visaNote: 'Belgian internship convention not required',
    applyType: 'Hosted apply',
    summary:
      'Paid traineeship supporting rail, clean mobility, and TEN-T advocacy campaigns.',
    responsibilities: [
      'Monitor TRAN committee activity and Council working parties.',
      'Draft newsletters and policy updates for members.',
      'Support event logistics during European Mobility Week.',
    ],
    requirements: [
      'Interest in transport, climate policy, or EU institutions.',
      'Strong written English and ability to summarise files quickly.',
      'Prior Brussels experience is helpful but not required.',
    ],
    benefits: ['Paid internship', 'Mentor', 'Networking events'],
    matchReasons: ['Paid internship', 'Deadline this week', 'Hybrid'],
    source: 'Verified NGO feed',
  },
  {
    id: 'eu-agency-comms-officer',
    title: 'Communications Officer',
    organisationId: 'european-security-agency',
    organisation: 'European Security Agency',
    logo: 'ES',
    city: 'The Hague',
    country: 'Netherlands',
    workMode: 'On-site',
    policyAreas: ['Security', 'Democracy'],
    category: 'Communications',
    seniority: 'Officer',
    contractType: 'Fixed term',
    languages: ['English', 'Dutch'],
    salaryMin: 59000,
    salaryMax: 72000,
    postedAt: '2026-06-15',
    deadline: '2026-07-20',
    verified: true,
    transparentSalary: true,
    visaNote: 'EU nationality required',
    applyType: 'External ATS',
    summary:
      'Deliver institutional communications for cyber resilience, crisis response, and democratic security programmes.',
    responsibilities: [
      'Run content calendars for policy launches and annual reports.',
      'Coordinate media lines with operational and legal teams.',
      'Prepare accessible visuals and social copy for public updates.',
    ],
    requirements: [
      '3+ years in institutional, agency, or public-sector communications.',
      'Experience with sensitive policy topics and approval workflows.',
      'Dutch is an advantage for local media coordination.',
    ],
    benefits: ['EU agency benefits', 'Relocation support', 'Training scheme'],
    matchReasons: ['Agency role', 'Security', 'Transparent grade'],
    source: 'Institutional feed',
  },
  {
    id: 'agri-food-campaign-lead',
    title: 'Agri-Food Campaign Lead',
    organisationId: 'soil-future-alliance',
    organisation: 'Soil Future Alliance',
    logo: 'SF',
    city: 'Vienna',
    country: 'Austria',
    workMode: 'Remote',
    policyAreas: ['Agriculture', 'Climate & Energy'],
    category: 'Programmes & Events',
    seniority: 'Manager',
    contractType: 'Fixed term',
    languages: ['English', 'German'],
    salaryMin: 61000,
    salaryMax: 72000,
    postedAt: '2026-06-12',
    deadline: '2026-07-26',
    verified: true,
    transparentSalary: true,
    visaNote: 'Remote in Austria, Germany, Belgium, or Netherlands',
    applyType: 'Email',
    summary:
      'Build a coalition campaign on soil health, farm transition funding, and sustainable food systems.',
    responsibilities: [
      'Coordinate NGOs, farmers, scientists, and foundation partners.',
      'Plan policy moments around AGRI committee votes and Council conclusions.',
      'Manage a small campaign budget and creative agency.',
    ],
    requirements: [
      'Campaign leadership experience in food, farming, climate, or biodiversity.',
      'Coalition management and excellent written advocacy skills.',
      'German language skills for Austrian and German partners.',
    ],
    benefits: ['Remote-first', 'Travel budget', 'Wellbeing allowance'],
    matchReasons: ['Remote', 'Agriculture', 'German useful'],
    source: 'Foundation partner',
  },
  {
    id: 'competition-associate',
    title: 'EU Competition Associate',
    organisationId: 'nord-law-europe',
    organisation: 'Nord Law Europe',
    logo: 'NL',
    city: 'Brussels',
    country: 'Belgium',
    workMode: 'On-site',
    policyAreas: ['Competition', 'Digital Policy'],
    category: 'Legal & Regulatory',
    seniority: 'Senior',
    contractType: 'Permanent',
    languages: ['English', 'French'],
    salaryEstimate: 'Competitive law firm package',
    postedAt: '2026-06-18',
    deadline: '2026-08-02',
    verified: true,
    visaNote: 'Bar admission route required',
    applyType: 'External ATS',
    summary:
      'Advise clients on EU competition, state aid, platform regulation, and merger control.',
    responsibilities: [
      'Draft submissions and economic evidence narratives.',
      'Support hearings and Commission engagement.',
      'Collaborate with digital regulatory and trade teams.',
    ],
    requirements: [
      'EU competition law experience from firm, authority, or consultancy.',
      'Excellent drafting and client-management skills.',
      'French is useful for Belgian proceedings and client work.',
    ],
    benefits: ['Bonus plan', 'Secondment options', 'Private health cover'],
    matchReasons: ['Competition', 'Law firm', 'Senior'],
    source: 'Recruiter package',
  },
  {
    id: 'eu-media-editor',
    title: 'EU Policy Editor',
    organisationId: 'policy-wire-europe',
    organisation: 'Policy Wire Europe',
    logo: 'PW',
    city: 'London',
    country: 'United Kingdom',
    workMode: 'Hybrid',
    policyAreas: ['Democracy', 'Financial Services', 'Trade'],
    category: 'Communications',
    seniority: 'Director',
    contractType: 'Permanent',
    languages: ['English'],
    salaryMin: 72000,
    salaryMax: 88000,
    postedAt: '2026-06-08',
    deadline: '2026-07-29',
    verified: true,
    transparentSalary: true,
    visaNote: 'UK work authorisation required',
    applyType: 'External ATS',
    summary:
      'Lead premium EU policy coverage for subscribers across London and Brussels.',
    responsibilities: [
      'Commission analysis on financial services, trade, and institutional politics.',
      'Edit daily briefings and manage two policy reporters.',
      'Host subscriber briefings with senior EU stakeholders.',
    ],
    requirements: [
      'Editorial leadership in EU policy, finance, or Westminster-Brussels coverage.',
      'Sharp judgement on subscriber value and regulatory detail.',
      'Confidence moderating senior policy conversations.',
    ],
    benefits: ['Subscriber-event budget', 'Hybrid newsroom', 'Editor bonus'],
    matchReasons: ['Media', 'Director level', 'Salary disclosed'],
    source: 'Media partner',
  },
  {
    id: 'education-programme-officer',
    title: 'Education Programme Officer',
    organisationId: 'european-learning-foundation',
    organisation: 'European Learning Foundation',
    logo: 'EL',
    city: 'Strasbourg',
    country: 'France',
    workMode: 'Hybrid',
    policyAreas: ['Education', 'Democracy'],
    category: 'Programmes & Events',
    seniority: 'Officer',
    contractType: 'Fixed term',
    languages: ['English', 'French'],
    salaryMin: 48000,
    salaryMax: 56000,
    postedAt: '2026-06-11',
    deadline: '2026-07-15',
    verified: true,
    transparentSalary: true,
    visaNote: 'French work authorisation required',
    applyType: 'Hosted apply',
    summary:
      'Manage grants, civic education projects, and youth participation events around European democracy.',
    responsibilities: [
      'Coordinate grantees across 12 countries and track deliverables.',
      'Prepare programme reports for institutional donors.',
      'Run Strasbourg workshops with civil society partners.',
    ],
    requirements: [
      'Programme management experience in education, democracy, or civil society.',
      'Comfort with grant reporting and multilingual stakeholders.',
      'French required for local partner coordination.',
    ],
    benefits: ['Training stipend', 'Extra leave days', 'Hybrid Strasbourg office'],
    matchReasons: ['Education', 'Hosted apply', 'French'],
    source: 'Direct employer',
  },
]
]
